---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon EKS Cluster'

Parameters:

  Version:
    Type: String
    Description: kubernetes cluster version

  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: ControlPlane SecurityGroup Ids

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: All subnets used by kubernetes

  ClusterRoleName:
    Type: String
    Default: eksServiceRole
    Description: EKS Service Role Name

Resources:
  ClusterRole: 
    Type: AWS::IAM::Role
    Properties: 
      RoleName: !Ref ClusterRoleName
      AssumeRolePolicyDocument: 
        Statement: 
          - 
            Action: 
              - "sts:AssumeRole"
            Effect: "Allow"
            Principal: 
              Service: 
                - "eks.amazonaws.com"
        Version: "2012-10-17"
      ManagedPolicyArns: 
        - "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
        - "arn:aws:iam::aws:policy/AmazonEKSServicePolicy"
      Path: "/"
  Cluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Sub '${AWS::StackName}-Cluster'
      Version: !Ref Version
      RoleArn: !GetAtt ClusterRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds: !Ref SecurityGroupIds
        SubnetIds: !Ref SubnetIds

Outputs:
  ClusterName:
    Description: EKS cluster name
    Value: !Ref Cluster